### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by andrewtheone** [S3bb1/ah-dashboard-plugin#14]
Whenever I try to login, it says user or password is wrong, but the background json returns my user (admin:admin) with the corrent first and last name and everything, but with a header: 400 Bad Request.

**Comment by S3bb1** [comment]
Hi,

which Version of ActionHero and which Version of the dashboard you use ? 

Does the ActionHero log shows any errors ?

Greetings

**Comment by supamii** [comment]
I also encountered the same issue with Actionhero 11 against the latest version of dashboard (3.X).
  I ran in the debugger and did not see any action assigned within actionhero's action processor.  Seems as though the actions aren't being loaded...

**Comment by S3bb1** [comment]
Hi,

can you try my latest commit ? I didnt released the latest Version wich is compatible with ActionHero 11.

Greetings

**Comment by supamii** [comment]
Yep, I did notice older connection vs data in the source I had yesterday so pulling down the latest definitely helped clear up the confusion.

However, it seems – for one reason or another – we’re not loading actions from the plugin’s /action/ folder.  I moved those files directly into my project’s action folder and only then is it loaded successfully.  I’m further confused because initializers and http files are being served from the plugin’s /public/ folder without any problems.

Additionally, I did not see anything that works around the case where the web server will not process simplyRouting.  In other words, there isn’t anything there dashboard specific /config/routes.js

I appreciate the quick response – let me know if you have any other pointers for me.
Huy.

**Comment by supamii** [comment]
Ok, I got it to load up – I’ll share some of this on github to possibly help out that other poor fellow.

To get the point, I actionHeroClient.js on the client-side relies on action query parameters so I had to make a few tweaks in my own to support it’s original purpose.  This explains why inbound http requests were flagged as unrecognized actions.

Grabbing your latest with actionhero11 updates helped a bunch too.

Thanks,
Huy.


From: Son-Huy Andrew Pham <sonhuy.pham@samsung.com<mailto:sonhuy.pham@samsung.com>>
Date: Saturday, June 20, 2015 at 1:46 PM
To: S3bb1/ah-dashboard-plugin <reply@reply.github.com<mailto:reply@reply.github.com>>, S3bb1/ah-dashboard-plugin <ah-dashboard-plugin@noreply.github.com<mailto:ah-dashboard-plugin@noreply.github.com>>
Subject: Re: [ah-dashboard-plugin] 400 Bad Request (#14)

Yep, I did notice older connection vs data in the source I had yesterday so pulling down the latest definitely helped clear up the confusion.

However, it seems – for one reason or another – we’re not loading actions from the plugin’s /action/ folder.  I moved those files directly into my project’s action folder and only then is it loaded successfully.  I’m further confused because initializers and http files are being served from the plugin’s /public/ folder without any problems.

Additionally, I did not see anything that works around the case where the web server will not process simplyRouting.  In other words, there isn’t anything there dashboard specific /config/routes.js

I appreciate the quick response – let me know if you have any other pointers for me.
Huy.

**Comment by supamii** [comment]
OH, I forgot to add:

Did you intend to remove http://localhost:8080/dashboard/bower_components/admin-lte/css/ionicons.min.css?

Maybe I should rephrase and ask why it’s missing?  I’m getting it on every page – as a part of the main dashboard.



From: Son-Huy Andrew Pham <sonhuy.pham@samsung.com<mailto:sonhuy.pham@samsung.com>>
Date: Saturday, June 20, 2015 at 2:28 PM
To: S3bb1/ah-dashboard-plugin <reply@reply.github.com<mailto:reply@reply.github.com>>, S3bb1/ah-dashboard-plugin <ah-dashboard-plugin@noreply.github.com<mailto:ah-dashboard-plugin@noreply.github.com>>
Subject: Re: [ah-dashboard-plugin] 400 Bad Request (#14)

Ok, I got it to load up – I’ll share some of this on github to possibly help out that other poor fellow.

To get the point, I actionHeroClient.js on the client-side relies on action query parameters so I had to make a few tweaks in my own to support it’s original purpose.  This explains why inbound http requests were flagged as unrecognized actions.

Grabbing your latest with actionhero11 updates helped a bunch too.

Thanks,
Huy.


From: Son-Huy Andrew Pham <sonhuy.pham@samsung.com<mailto:sonhuy.pham@samsung.com>>
Date: Saturday, June 20, 2015 at 1:46 PM
To: S3bb1/ah-dashboard-plugin <reply@reply.github.com<mailto:reply@reply.github.com>>, S3bb1/ah-dashboard-plugin <ah-dashboard-plugin@noreply.github.com<mailto:ah-dashboard-plugin@noreply.github.com>>
Subject: Re: [ah-dashboard-plugin] 400 Bad Request (#14)

Yep, I did notice older connection vs data in the source I had yesterday so pulling down the latest definitely helped clear up the confusion.

However, it seems – for one reason or another – we’re not loading actions from the plugin’s /action/ folder.  I moved those files directly into my project’s action folder and only then is it loaded successfully.  I’m further confused because initializers and http files are being served from the plugin’s /public/ folder without any problems.

Additionally, I did not see anything that works around the case where the web server will not process simplyRouting.  In other words, there isn’t anything there dashboard specific /config/routes.js

I appreciate the quick response – let me know if you have any other pointers for me.
Huy.

**Comment by andrewtheone** [comment]
Now I'm getting:

        stringResponse = JSON.stringify(data.response, null, api.config.server
                              ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at completeResponse (D:\Projects\Test\COS\node_modules\actionhero\servers\we
b.js:268:31)
    at null.<anonymous> (D:\Projects\Test\COS\node_modules\actionhero\servers\we
b.js:145:5)
    at emit (events.js:107:17)
    at null.callback (D:\Projects\Test\COS\node_modules\actionhero\initializers\
genericServer.js:89:14)
    at D:\Projects\Test\COS\node_modules\actionhero\initializers\actionProcessor
.js:87:16
    at process._tickDomainCallback (node.js:381:11)


bot AH and Dashboard the latest. no modification, clean install.

**Comment by andrewtheone** [comment]
Okay I traced down the error: So, the first error, I fixed it with modifying the actionhero web.js ...

268. line:
        
var cache = [];

        stringResponse = JSON.stringify(data.response, function(key, value) {
    if (typeof value === 'object' && value !== null) {
        if (cache.indexOf(value) !== -1) {
            // Circular reference found, discard key
            return;
        }
        // Store value in our collection
        cache.push(value);
    }
    return value;
}, api.config.servers.web.padding);
        cache = null; // Enable garbage collection

And then, I found out that dasboard plugin, calls action's next's callback with 2 paramters first parameter is connection the second one is a boolean, which is totally incorrect, actionhero only excepts one parameter a null or object (null - no error, object = error), so because the next(connection, true) first parameters is a object, its always an error code...

i fixed it with modifying ah's actionProcessor.js - 291th line:

            if(error == null) {
              return;
            }

            if(typeof error == "object") {
              if(error.error == null) {
                self.completeAction();
                return;
              }
            }

**Comment by andrewtheone** [comment]
Due to actionhero modifications, certain actionhero parts became malfunctionee... so its not a permament solution

**Comment by supamii** [comment]
I've seen that since actionhero is slow to update the config/errors.js file.  For one reason or another it went from JSON objects to Error objects and doesn't yet check to see if it's of type String.

That error you're getting is not the root cause of the issue, but it needs to be dealt with.

**Comment by supamii** [comment]
Last thing i'll note - i'll probably just have to submit a merge request but --- is that the new actionhero statuses return an "uptimeMinutes" property in api::stats - to get the nice uptime value, just set

// In the *DEFAULT* status.js action 
data.response.uptime = (now - api.bootTime);
data.response.uptimeMinutes = Math.round(data.response.uptime / 60000);

**Comment by S3bb1** [comment]
Hi all,

thank you for the analysis. I will try to reproduce them with the current ActionHero, because in my tests all was working well in the dashboard. I have not so mich time currently :-/ so i'll do my best.

Greetings

**Comment by supamii** [comment]
For the benefit of others - I submitted various fixes for actionhero v11 - pending a pull

**Comment by supamii** [comment]
https://github.com/S3bb1/ah-dashboard-plugin/pull/17
